#!/bin/sh

mkdir -p ipkg/home/retrofw/games/dividead
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/games
cp ./DiviDeadRS97.elf ipkg/home/retrofw/games/dividead/dividead
cp ./RES/DC/icon.png ipkg/home/retrofw/games/dividead/dividead.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: dividead
Version: 1.0
Description: Visual novel
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/divi-dead
Depends:
Source: https://github.com/gameblabla/divi-dead' > control

print '2.0' > debian-binary

print 'title=Divi-Dead
description=Visual novel game
exec=/home/retrofw/games/dividead/dividead
clock=600
selectordir=/home/retrofw
selectorfilter=.dl1,.DL1' > home/retrofw/apps/gmenu2x/sections/games/dividead

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../dividead.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
