#include <windows.h>

#undef  HOOK_INIT_VIDEO_PRE
#define HOOK_INIT_VIDEO_PRE() WIN_HOOK_INIT_VIDEO_PRE()

#undef  HOOK_AUDIO_FREQ
#define HOOK_AUDIO_FREQ     44100

#undef  HOOK_AUDIO_FORMAT
#define HOOK_AUDIO_FORMAT   AUDIO_S16SYS

#undef  HOOK_AUDIO_CHANNELS
#define HOOK_AUDIO_CHANNELS 2
